import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service - iAura",
  description: "iAura Terms of Service - Read the terms and conditions governing your use of iAura.",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0D1117]">
      {/* Header */}
      <nav className="border-b border-white/5 bg-[#0D1117]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold">
            <span className="text-gray-400">i</span>
            <span className="gradient-text">Aura</span>
          </Link>
          <Link href="/" className="text-sm text-gray-400 hover:text-white transition-colors">
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-12">Last updated: February 8, 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using the iAura mobile application (the &ldquo;App&rdquo;) or visiting our website at iaura.app (the &ldquo;Website&rdquo;), collectively referred to as the &ldquo;Services,&rdquo; you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, you may not access or use the Services.
            </p>
            <p>
              These Terms constitute a legally binding agreement between you and iAura (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). We reserve the right to modify these Terms at any time. Your continued use of the Services after any changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">2. Eligibility</h2>
            <p>
              You must be at least 13 years of age (or 16 in the European Economic Area) to use our Services. By using the Services, you represent and warrant that you meet this age requirement. If you are under the age of 18, you must have the consent of a parent or legal guardian to use the Services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">3. Account Registration</h2>
            <p>
              To use certain features of the Services, you must create an account. You agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Maintain the security and confidentiality of your login credentials</li>
              <li>Accept responsibility for all activities that occur under your account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
            </ul>
            <p>
              We reserve the right to suspend or terminate your account if any information provided is inaccurate, incomplete, or violates these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">4. Services Description</h2>
            <p>
              iAura provides an AI-powered personality analysis service that:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Records and transcribes voice recordings you provide</li>
              <li>Analyzes the transcribed content to generate a personality profile</li>
              <li>Creates unique aura images based on the personality analysis</li>
              <li>Stores your generated auras in a personal gallery</li>
            </ul>
            <p>
              The personality analyses and aura images are generated by artificial intelligence and are intended for entertainment and self-reflection purposes only. They should not be considered as professional psychological or medical assessments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">5. Credits and Purchases</h2>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">5.1 Credit System</h3>
            <p>
              The App uses a credit-based system. Each credit allows you to generate one complete aura (including voice analysis, personality profile, and aura image generation). New accounts receive 3 free credits upon registration.
            </p>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">5.2 Purchasing Credits</h3>
            <p>
              Additional credits can be purchased through the App via Apple&apos;s In-App Purchase system. Available credit packs include:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Basic Pack: 5 credits for $4.99 USD</li>
              <li>Premium Pack: 20 credits for $9.99 USD</li>
              <li>Unlimited Pack: Unlimited credits for $19.99 USD</li>
            </ul>
            <p>
              All prices are in US dollars and may vary by region. Prices are subject to change without prior notice.
            </p>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">5.3 Refund Policy</h3>
            <p>
              All purchases are processed through Apple&apos;s App Store and are subject to Apple&apos;s refund policies. Credits are non-transferable and cannot be exchanged for cash. We do not provide refunds for used credits. For unused credit packs, please contact Apple Support for refund assistance.
            </p>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">5.4 Credit Expiration</h3>
            <p>
              Purchased credits do not expire. However, credits may be forfeited if your account is terminated due to a violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">6. User Content</h2>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">6.1 Your Content</h3>
            <p>
              You retain ownership of the voice recordings you submit and the content of your speech. By using the Services, you grant us a limited, non-exclusive license to process your voice recordings for the sole purpose of providing the Services.
            </p>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">6.2 Generated Content</h3>
            <p>
              The personality analyses and aura images generated by our AI are provided to you for personal, non-commercial use. You may share these generated works on social media and personal platforms. You may not sell, license, or commercially distribute the generated content without our prior written consent.
            </p>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">6.3 Prohibited Content</h3>
            <p>You agree not to submit voice recordings that contain:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Hate speech, threats, or incitement to violence</li>
              <li>Sexually explicit or obscene material</li>
              <li>Content that infringes on any third party&apos;s intellectual property rights</li>
              <li>Personal information of others without their consent</li>
              <li>Any content that violates applicable laws or regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">7. Intellectual Property</h2>
            <p>
              The Services, including the App, Website, and all content, features, and functionality (including but not limited to the design, algorithms, software, text, graphics, logos, and trademarks), are owned by iAura and are protected by international copyright, trademark, and other intellectual property laws.
            </p>
            <p>
              You are granted a limited, non-exclusive, non-transferable, revocable license to use the App for personal, non-commercial purposes in accordance with these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">8. Prohibited Uses</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Services for any illegal or unauthorized purpose</li>
              <li>Attempt to reverse engineer, decompile, or disassemble the App</li>
              <li>Interfere with or disrupt the Services or servers connected to the Services</li>
              <li>Use automated means to access the Services (bots, scrapers, etc.)</li>
              <li>Circumvent any security or authentication measures</li>
              <li>Impersonate another person or entity</li>
              <li>Use the Services to harass, abuse, or harm another person</li>
              <li>Attempt to gain unauthorized access to other users&apos; accounts</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">9. Disclaimer of Warranties</h2>
            <p>
              THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p>
              WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT ANY DEFECTS WILL BE CORRECTED. THE PERSONALITY ANALYSES AND AURA IMAGES ARE GENERATED BY AI AND MAY NOT ACCURATELY REFLECT YOUR ACTUAL PERSONALITY OR CHARACTERISTICS.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">10. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL IAURA, ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES.
            </p>
            <p>
              OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATING TO THE SERVICES SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">11. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless iAura and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or related to your use of the Services, your violation of these Terms, or your violation of any rights of another.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">12. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Services immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Services will immediately cease. All provisions of these Terms that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Switzerland, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Zurich, Switzerland.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">14. Severability</h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">15. Contact Us</h2>
            <p>
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <ul className="list-none space-y-1 mt-3">
              <li><strong>Brand Agent GmbH</strong></li>
              <li>Hammerstrasse 5, 6312 Steinhausen</li>
              <li>UID: CHE-204.407.181</li>
              <li>Email: <a href="mailto:info@brandagent.ch" className="text-[#00C9B8] hover:underline">info@brandagent.ch</a></li>
            </ul>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8">
        <div className="max-w-4xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-gray-600 text-sm">&copy; {new Date().getFullYear()} Brand Agent GmbH. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="text-sm text-gray-500 hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/" className="text-sm text-gray-500 hover:text-white transition-colors">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
