import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - iAura",
  description: "iAura Privacy Policy - Learn how we collect, use, and protect your personal information.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#0D1117]">
      {/* Header */}
      <nav className="border-b border-white/5 bg-[#0D1117]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold">
            <span className="text-gray-400">i</span>
            <span className="gradient-text">Aura</span>
          </Link>
          <Link href="/" className="text-sm text-gray-400 hover:text-white transition-colors">
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-gray-500 text-sm mb-12">Last updated: February 8, 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">1. Introduction</h2>
            <p>
              Welcome to iAura (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). We are committed to protecting your privacy and personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application iAura (the &ldquo;App&rdquo;) and our website (together, the &ldquo;Services&rdquo;).
            </p>
            <p>
              By using our Services, you agree to the collection and use of information in accordance with this policy. If you do not agree with the terms of this Privacy Policy, please do not access or use our Services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">2. Information We Collect</h2>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">2.1 Information You Provide</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Account Information:</strong> When you create an account, we collect your email address and any profile information you choose to provide.</li>
              <li><strong>Voice Recordings:</strong> When you use the aura generation feature, you provide a voice recording. These recordings are processed in real-time and are NOT stored on our servers after analysis is complete.</li>
              <li><strong>Purchase Information:</strong> When you purchase credits, the transaction is processed by Apple through the App Store. We do not collect or store your payment card details.</li>
            </ul>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">2.2 Information Generated by Our Services</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Transcription Text:</strong> The text transcription generated from your voice recording.</li>
              <li><strong>Personality Analysis:</strong> The AI-generated personality analysis results, including traits, themes, and color associations.</li>
              <li><strong>Aura Images:</strong> The AI-generated aura images created based on your personality analysis.</li>
            </ul>

            <h3 className="text-lg font-medium text-gray-200 mt-6 mb-3">2.3 Automatically Collected Information</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Device Information:</strong> Device type, operating system version, and unique device identifiers.</li>
              <li><strong>Usage Data:</strong> Information about how you use the App, including features used, timestamps, and interaction patterns.</li>
              <li><strong>Log Data:</strong> Error logs and performance data to help us improve the App.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">3. How We Use Your Information</h2>
            <p>We use the collected information for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide, maintain, and improve our Services</li>
              <li>To process your voice recordings and generate personality analyses and aura images</li>
              <li>To manage your account and provide customer support</li>
              <li>To process transactions and manage your credit balance</li>
              <li>To send you technical notices, updates, and administrative messages</li>
              <li>To detect, prevent, and address technical issues and security threats</li>
              <li>To comply with legal obligations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">4. Data Processing and Third-Party Services</h2>
            <p>To provide our AI-powered features, we use the following third-party services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Supabase:</strong> For authentication, database storage, and file storage. Data is stored in secure, encrypted databases.</li>
              <li><strong>OpenAI (GPT-4 and DALL-E 3):</strong> For personality analysis and aura image generation. Voice transcriptions are sent to OpenAI for processing. OpenAI&apos;s data usage policies apply.</li>
              <li><strong>Apple App Store:</strong> For processing in-app purchases and managing subscriptions.</li>
            </ul>
            <p>
              We ensure that all third-party service providers maintain appropriate security measures and handle your data in accordance with applicable data protection laws.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">5. Data Retention</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Voice Recordings:</strong> Deleted immediately after processing. We do not retain your voice recordings.</li>
              <li><strong>Personality Analyses and Aura Images:</strong> Retained in your account until you delete them or delete your account.</li>
              <li><strong>Account Information:</strong> Retained as long as your account is active. Upon account deletion, your data is permanently removed within 30 days.</li>
              <li><strong>Usage Data:</strong> Retained for up to 12 months for analytics purposes, then aggregated or deleted.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">6. Data Security</h2>
            <p>
              We implement appropriate technical and organizational security measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. These measures include:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Encryption of data in transit (TLS/SSL) and at rest</li>
              <li>Secure authentication mechanisms</li>
              <li>Regular security assessments and updates</li>
              <li>Access controls and monitoring</li>
            </ul>
            <p>
              However, no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">7. Your Rights (GDPR)</h2>
            <p>
              If you are a resident of the European Economic Area (EEA), you have certain data protection rights under the General Data Protection Regulation (GDPR):
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Right of Access:</strong> You can request a copy of your personal data.</li>
              <li><strong>Right to Rectification:</strong> You can request correction of inaccurate personal data.</li>
              <li><strong>Right to Erasure:</strong> You can request deletion of your personal data.</li>
              <li><strong>Right to Restrict Processing:</strong> You can request that we limit how we use your data.</li>
              <li><strong>Right to Data Portability:</strong> You can request a copy of your data in a structured, machine-readable format.</li>
              <li><strong>Right to Object:</strong> You can object to our processing of your personal data.</li>
            </ul>
            <p>
              To exercise any of these rights, please contact us at <a href="mailto:privacy@iaura.app" className="text-[#00C9B8] hover:underline">privacy@iaura.app</a>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">8. Children&apos;s Privacy</h2>
            <p>
              Our Services are not intended for children under the age of 13 (or 16 in the EEA). We do not knowingly collect personal information from children. If we become aware that we have collected personal data from a child without parental consent, we will take steps to delete that information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">9. International Data Transfers</h2>
            <p>
              Your information may be transferred to and maintained on servers located outside of your country of residence. We ensure that appropriate safeguards are in place for such transfers, including Standard Contractual Clauses approved by the European Commission where applicable.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">10. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &ldquo;Last updated&rdquo; date. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mt-10 mb-4">11. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy or our data practices, please contact us at:
            </p>
            <ul className="list-none space-y-1 mt-3">
              <li>Email: <a href="mailto:privacy@iaura.app" className="text-[#00C9B8] hover:underline">privacy@iaura.app</a></li>
              <li>Website: <a href="https://iaura.app" className="text-[#00C9B8] hover:underline">iaura.app</a></li>
            </ul>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8">
        <div className="max-w-4xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-gray-600 text-sm">&copy; {new Date().getFullYear()} iAura. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/terms" className="text-sm text-gray-500 hover:text-white transition-colors">Terms of Service</Link>
            <Link href="/" className="text-sm text-gray-500 hover:text-white transition-colors">Home</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
